domain_path: C:\Users\miro\ece-315-lab\lab1\sw\lab1_platform\export\lab1_platform\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
