# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/lab1_hw/lab1_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw || ORIG_REF_NAME==lab1_hw} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_processing_system7_0_0/lab1_hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_processing_system7_0_0 || ORIG_REF_NAME==lab1_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_axi_gpio_0_0/lab1_hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_axi_gpio_0_0 || ORIG_REF_NAME==lab1_hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_axi_gpio_0_1/lab1_hw_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_axi_gpio_0_1 || ORIG_REF_NAME==lab1_hw_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_axi_smc_0/lab1_hw_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_axi_smc_0 || ORIG_REF_NAME==lab1_hw_axi_smc_0} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_rst_ps7_0_50M_0/lab1_hw_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==lab1_hw_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_axi_gpio_1_1/lab1_hw_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_axi_gpio_1_1 || ORIG_REF_NAME==lab1_hw_axi_gpio_1_1} -quiet] -quiet

# IP: bd/lab1_hw/ip/lab1_hw_axi_gpio_2_0/lab1_hw_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab1_hw_axi_gpio_2_0 || ORIG_REF_NAME==lab1_hw_axi_gpio_2_0} -quiet] -quiet

# XDC: c:/Users/miro/ece-315-lab/lab1/hw/ece315_lab1/ece315_lab1.gen/sources_1/bd/lab1_hw/lab1_hw_ooc.xdc
